// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const IconCarbonTouch1: typeof import('~icons/carbon/touch1.jsx')['default']
  const IconIcOutlineMotionPhotosAuto: typeof import('~icons/ic/outline-motion-photos-auto.jsx')['default']
  const IconRiHeart2Fill: typeof import('~icons/ri/heart2-fill.jsx')['default']
  const IconRiRestartLine: typeof import('~icons/ri/restart-line.jsx')['default']
  const IconRiRotateLockLine: typeof import('~icons/ri/rotate-lock-line.jsx')['default']
}
export {}
